### ISSUE TITLE
f.getClientRects is not a function

### ISSUE THREAD

**Issue by Jasin2069** [itsjavi/bootstrap-popover-picker#14]
This looks exactly like what I am working for but I am currently having issues. Is there a way to get this to work with JQuery 3+? Currently using 3.1.1 I keep getting this error when testing
"f.getClientRects is not a function"

**Comment by Jasin2069** [comment]
I was able to get around this issue currently by using the migrate script.
http://code.jquery.com/jquery-migrate-3.0.0.js
